name: "Authenticate to Environment"
description: "Authenticate to a Salesforce environment using SFP Server"
author: "flxbl-io"

branding:
  icon: "anchor"
  color: "green"

inputs:
  environment:
    description: "Name of the environment to authenticate"
    required: true
  repository:
    description: "Repository name (format: owner/repo)"
    required: false
    default: ${{ github.repository }}
  sfp-server-url:
    description: "URL to the SFP Server instance (e.g., https://your-org.flxbl.io)"
    required: true
  sfp-server-token:
    description: "Token for SFP Server authentication"
    required: true
  alias:
    description: "Alias for the authenticated environment org (defaults to environment name)"
    required: false
    default: ""
outputs:
  alias:
    description: "Alias used for the authenticated org"
    value: ${{ steps.auth.outputs.alias }}

runs:
  using: "composite"

  steps:
    - name: Print header
      shell: bash
      run: |
        echo "------------------------------------------------------------------------------------------"
        echo "flxbl-actions  -- ❤️  by flxbl.io ❤️  -Version:1.0.0"
        echo "------------------------------------------------------------------------------------------"
        echo "Action     : auth-environment"
        echo "Environment : ${{ inputs.environment }}"
        echo "Repository  : ${{ inputs.repository }}"
        echo "SFP Server  : ${{ inputs.sfp-server-url }}"
        echo "------------------------------------------------------------------------------------------"

    - name: Authenticate to Environment
      id: auth
      shell: bash
      env:
        SFP_SERVER_URL: ${{ inputs.sfp-server-url }}
        SFP_SERVER_TOKEN: ${{ inputs.sfp-server-token }}
      run: |
        echo "Authenticating to environment '${{ inputs.environment }}' via SFP Server..."

        # Build command with optional flags
        CMD="sfp server environment login --name \"${{ inputs.environment }}\" --repository \"${{ inputs.repository }}\""

        if [[ -n "${{ inputs.alias }}" ]]; then
          CMD="$CMD --alias \"${{ inputs.alias }}\""
          TARGET_ALIAS="${{ inputs.alias }}"
        else
          TARGET_ALIAS="${{ inputs.environment }}"
        fi

        eval $CMD

        echo "::notice::Successfully authenticated to environment '${{ inputs.environment }}'"
        echo "alias=$TARGET_ALIAS" >> $GITHUB_OUTPUT
